In [1]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
len(alphabets)

26

In [ ]:

alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

char_to_num = {}

for i in range(len(alphabets)):
    letter = alphabets[i]
    char_to_num[letter] = i

print(char_to_num)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9, 'K': 10, 'L': 11, 'M': 12, 'N': 13, 'O': 14, 'P': 15, 'Q': 16, 'R': 17, 'S': 18, 'T': 19, 'U': 20, 'V': 21, 'W': 22, 'X': 23, 'Y': 24, 'Z': 25}


In [4]:
int_to_char = dict(enumerate(alphabets))
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [5]:
char_to_int = dict((v, i) for i, v in enumerate(alphabets))
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

#### prepare the data

In [10]:
# Assuming 'alphabets' is already defined: alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
seq_length = 1
x = []
y = []

# Populate x and y
for i in range(len(alphabets) - seq_length):
    seq_in = [alphabets[i]]
    seq_out = alphabets[i + 1]
    
    print(seq_in, '-->', seq_out)
    
    x += [[char_to_int[seq_in[0]]]]
    y += [char_to_int[seq_out]]

['A'] --> B
['B'] --> C
['C'] --> D
['D'] --> E
['E'] --> F
['F'] --> G
['G'] --> H
['H'] --> I
['I'] --> J
['J'] --> K
['K'] --> L
['L'] --> M
['M'] --> N
['N'] --> O
['O'] --> P
['P'] --> Q
['Q'] --> R
['R'] --> S
['S'] --> T
['T'] --> U
['U'] --> V
['V'] --> W
['W'] --> X
['X'] --> Y
['Y'] --> Z


In [11]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [12]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [13]:
import numpy as np

In [15]:
x =np.reshape(x, (25,1,1))
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [16]:
x_scaled = x/25
x_scaled

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [17]:
from keras.utils import to_categorical

In [20]:
y_new = to_categorical(y)
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [21]:
y_new.shape

(25, 26)

#### Build the model

In [25]:
from keras.layers import SimpleRNN, Input, Dense
from keras.models import Sequential


In [27]:
model = Sequential()

model.add(Input((1,1)))
model.add(Dense(32, activation = 'relu'))
model.add(SimpleRNN(32))
model.add(Dense(26, activation = 'softmax'))

In [28]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 1, 32)          │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 26)             │           858 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,002 (11.73 KB)

 Trainable params: 3,002 (11.73 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.compile(loss='categorical_crossentropy',
              optimizer ='adam', metrics=['accuracy'])

In [ ]:
# model.fit(x_scaled, y_new, batch_size=1, epochs=500)

Epoch 1/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0000e+00 - loss: 3.2756
Epoch 2/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0800 - loss: 3.2563   
Epoch 3/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.2467    
Epoch 4/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.2409   
Epoch 5/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.2323   
Epoch 6/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 3.2267
Epoch 7/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0400 - loss: 3.2167   
Epoch 8/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 3.2077
Epoch 9/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 3.1964
Epoch 10/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.1851   
Epoch 11/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.1735   
Epoch 12/500
25/25 ━━━━━━

In [31]:
model.fit(x_scaled, y_new, batch_size=1, epochs=1000)

Epoch 1/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8800 - loss: 1.1244
Epoch 2/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8400 - loss: 1.1187
Epoch 3/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8400 - loss: 1.1175
Epoch 4/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8800 - loss: 1.1140
Epoch 5/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8800 - loss: 1.1127
Epoch 6/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8400 - loss: 1.1099   
Epoch 7/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9200 - loss: 1.1108
Epoch 8/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8800 - loss: 1.1112
Epoch 9/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8800 - loss: 1.1132
Epoch 10/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8000 - loss: 1.1144
Epoch 11/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8400 - loss: 1.1067
Epoch 12/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/s

In [32]:
model.evaluate(x_scaled, y_new, batch_size=1)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9600 - loss: 0.2909


[0.2909279763698578, 0.9599999785423279]

In [33]:
new_char = 'K'

In [40]:
input_val = char_to_int['K'] / 25.0

input_reshaped = np.reshape(input_val, (1, 1, 1))

prediction = model.predict(input_reshaped)

predicted_index = np.argmax(prediction)

predicted_char = int_to_char[predicted_index]

print(f"character after '{new_char}' is '{predicted_char}'")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
character after 'K' is 'L'


In [41]:
new_char = 'K'
new_char = char_to_int[new_char]
new_char = np.reshape(new_char,(1,1,1))
new_char = new_char / 25
pred = model.predict(new_char)
int_to_char[pred.argmax()]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


'L'

In [43]:
new_char = 'Z'
new_char = char_to_int[new_char]
new_char = np.reshape(new_char,(1,1,1))
new_char = new_char / 25
pred = model.predict(new_char)
int_to_char[pred.argmax()]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


'Z'

In [45]:
# Assuming 'alphabets' is already defined: alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
seq_length = 3
x = []
y = []

# Populate x and y
for i in range(len(alphabets) - seq_length):
    seq_in = alphabets[i:i+seq_length]
    seq_out = alphabets[i + seq_length]
    
    print(seq_in, '-->', seq_out)
    
    x.append([char_to_int[char] for char in seq_in])
    y += [char_to_int[seq_out]]

ABC --> D
BCD --> E
CDE --> F
DEF --> G
EFG --> H
FGH --> I
GHI --> J
HIJ --> K
IJK --> L
JKL --> M
KLM --> N
LMN --> O
MNO --> P
NOP --> Q
OPQ --> R
PQR --> S
QRS --> T
RST --> U
STU --> V
TUV --> W
UVW --> X
VWX --> Y
WXY --> Z


In [46]:
x_new = np.reshape(x, (23, seq_length, 1))

In [47]:
y_new = to_categorical(y)

In [48]:
x_new.shape, y_new.shape

((23, 3, 1), (23, 26))

In [49]:
x_new = x_new / 25

In [50]:
model = Sequential()

model.add(Input((3,1)))
model.add(Dense(32, activation = 'relu'))
model.add(SimpleRNN(32))
model.add(Dense(26, activation = 'softmax'))

In [51]:
model.compile(loss='categorical_crossentropy',
              optimizer ='adam', metrics=['accuracy'])

In [52]:
model.fit(x_new, y_new, batch_size=1, epochs=1000)

Epoch 1/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0435 - loss: 3.3353  
Epoch 2/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0435 - loss: 3.2734   
Epoch 3/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0435 - loss: 3.2422   
Epoch 4/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0870 - loss: 3.2136   
Epoch 5/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0435 - loss: 3.1830   
Epoch 6/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0870 - loss: 3.1529   
Epoch 7/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0870 - loss: 3.1186   
Epoch 8/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0870 - loss: 3.0886   
Epoch 9/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0870 - loss: 3.0493   
Epoch 10/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0870 - loss: 3.0063   
Epoch 11/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0870 - loss: 2.9583   
Epoch 12/1000
23/23 

In [53]:
model.evaluate(x_new, y_new, batch_size=1)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9130 - loss: 0.1450    


[0.14498627185821533, 0.9130434989929199]

In [58]:
new_char = 'KLM'
new_char = [char_to_int[char] for char in 'KLM']
new_char = np.reshape(new_char,(1,3,1))
new_char = new_char / 25
pred = model.predict(new_char, verbose = 0)
int_to_char[pred.argmax()]

'N'

In [61]:
new_char = 'STU'
new_char = [char_to_int[char] for char in new_char]
new_char = np.reshape(new_char,(1,3,1))
new_char = new_char / 25
pred = model.predict(new_char, verbose = 0)
int_to_char[pred.argmax()]

'V'